name: publish_from_ideas

on:
  # 08:15 JST (= 23:15 UTC) に 1 日 1 回実行
  schedule:
    - cron: '15 23 * * *'
  # 手動トリガーも可能
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # push するので write 権限を明示

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          # OpenAI v1 系 + 投稿用ライブラリ
          pip install "openai>=1.3" markdown \
                     python-frontmatter requests python-slugify

      # ────────── 記事生成 ──────────
      - name: Generate markdown article (1/day)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/generate_from_ideas.py

      # ────────── 生成ファイルをコミット ──────────
      - name: Commit & push generated posts
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/sabou/*.md
          git diff --cached --quiet || git commit -m "chore: auto-generate sabou posts"
          git push

      # ────────── WordPress に公開 ──────────
      - name: Post latest markdown to WordPress
        env:
          WP_URL:       ${{ secrets.WP_URL }}
          WP_USER:      ${{ secrets.WP_USER }}
          WP_APP_PASS:  ${{ secrets.WP_APP_PASS }}
        run: |
          python scripts/post_to_wp.py
